/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/selectHour`; params?: Router.UnknownInputParams; } | { pathname: `/prenotazioni`; params?: Router.UnknownInputParams; } | { pathname: `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/update-password`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/management` | `/management`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profilo` | `/profilo`; params?: Router.UnknownInputParams; } | { pathname: `/utils/client`; params?: Router.UnknownInputParams; } | { pathname: `/utils/supabase`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `/createAccount`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/selectHour`; params?: Router.UnknownOutputParams; } | { pathname: `/prenotazioni`; params?: Router.UnknownOutputParams; } | { pathname: `/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `/update-password`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/management` | `/management`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profilo` | `/profilo`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/client`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/supabase`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/calendar${`?${string}` | `#${string}` | ''}` | `/createAccount${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/selectHour${`?${string}` | `#${string}` | ''}` | `/prenotazioni${`?${string}` | `#${string}` | ''}` | `/reset-password${`?${string}` | `#${string}` | ''}` | `/update-password${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/management${`?${string}` | `#${string}` | ''}` | `/management${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profilo${`?${string}` | `#${string}` | ''}` | `/profilo${`?${string}` | `#${string}` | ''}` | `/utils/client${`?${string}` | `#${string}` | ''}` | `/utils/supabase${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/selectHour`; params?: Router.UnknownInputParams; } | { pathname: `/prenotazioni`; params?: Router.UnknownInputParams; } | { pathname: `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/update-password`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/management` | `/management`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profilo` | `/profilo`; params?: Router.UnknownInputParams; } | { pathname: `/utils/client`; params?: Router.UnknownInputParams; } | { pathname: `/utils/supabase`; params?: Router.UnknownInputParams; };
    }
  }
}
